# Usar una imagen base de .NET SDK
FROM mcr.microsoft.com/dotnet/sdk:9.0.102

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo C# al contenedor
COPY . /app


# Ejecutar el código C# cuando el contenedor se inicie
CMD ["dotnet", "run"]
